fix(CMake): update FatFs source paths to include 'third_party' directory

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -42,9 +42,9 @@ jobs:
 
       - name: Static analysis
         run: |
-          export FATFS_INCLUDE=$GITHUB_WORKSPACE/pico-sdk/lib/tinyusb/lib/fatfs/source
+          export FATFS_INCLUDE=$GITHUB_WORKSPACE/third_party/pico-sdk/lib/tinyusb/lib/fatfs/source
           bash scripts/static_analysis.sh
 
       - name: List FatFs files
-        run: ls -l pico-sdk/lib/tinyusb/lib/fatfs/source || echo "Not found"
+        run: ls -l third_party/pico-sdk/lib/tinyusb/lib/fatfs/source || echo "Not found"
 
